name: PHP Composer

on:
  push:
    branches: [ "main", "release" ]
  pull_request:
    branches: [ "main", "release" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Require Pest
      run: composer require pestphp/pest --dev --with-all-dependencies
      
    - name: Pest init
      run: vendor/bin/pest --init

    - name: Pest run tests
      run: vendor/bin/pest --coverage-clover clover.xml

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Generate test coverage badge
      uses: timkrase/phpunit-coverage-badge@v1.2.0
      with:
        coverage_badge_path: 'badge-coverage.svg'
        push_badge: true
        repo_token: ${{ secrets.GITHUB_TOKEN }}
